name: drewpoulson
favicon: null
layout_spectrum: 0.74065
typography_spectrum: 0.32505
title: Drew Poulson Portfolio
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#b8b8b8'
    - '#010101'
    - '#af0001'
    - '#373737'
  brandStrength: 0.3207093549426645
  lightness: 0.4599993552546948
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
